version: '2.3'

services:
  mas-redis:
    restart: always
    image: redis:4.0
    container_name: mas-redis
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6379:6379"

  mas-tc:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: mas_image:latest
    container_name: mas-tc
    command: goreman -f Procfile2 start
    ports:
      - "9008:9008"

  mas-rm-1:
    restart: always
    image: mas_image:latest
    container_name: mas-rm-1
    command: >
      bash -c "echo 'raftgroup1-1: go run main.go --mode rm --clusterid 1 --id 1 --cluster http://127.0.0.1:12379 --raftport :12379 --rmport :50041 --db mas' > ./Procfile |
      goreman start"
    depends_on:
      - mas-tc

  mas-rm-2:
    restart: always
    image: mas_image:latest
    container_name: mas-rm-2
    command: >
      bash -c "echo 'raftgroup1-1: go run main.go --mode rm --clusterid 2 --id 1 --cluster http://127.0.0.1:12379 --raftport :12379 --rmport :50041 --db mas' > ./Procfile |
      goreman start"
    depends_on:
          - mas-tc

  mas-rm-3:
    restart: always
    image: mas_image:latest
    container_name: mas-rm-3
    command: >
      bash -c "echo 'raftgroup1-1: go run main.go --mode rm --clusterid 3 --id 1 --cluster http://127.0.0.1:12379 --raftport :12379 --rmport :50041 --db mas' > ./Procfile |
      goreman start"
    depends_on:
          - mas-tc

volumes:
  mas:
    driver: local
  redis:
    driver: local

networks:
  mysqlnetwork:
    driver: bridge