// Code generated by protoc-gen-go. DO NOT EDIT.
// source: txn_request.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type DepositRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositRequest) Reset()         { *m = DepositRequest{} }
func (m *DepositRequest) String() string { return proto.CompactTextString(m) }
func (*DepositRequest) ProtoMessage()    {}
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5080b223cb4cee2, []int{0}
}

func (m *DepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositRequest.Unmarshal(m, b)
}
func (m *DepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositRequest.Marshal(b, m, deterministic)
}
func (m *DepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositRequest.Merge(m, src)
}
func (m *DepositRequest) XXX_Size() int {
	return xxx_messageInfo_DepositRequest.Size(m)
}
func (m *DepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositRequest proto.InternalMessageInfo

func (m *DepositRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DepositRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// The response message containing the greetings
type DepositReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositReply) Reset()         { *m = DepositReply{} }
func (m *DepositReply) String() string { return proto.CompactTextString(m) }
func (*DepositReply) ProtoMessage()    {}
func (*DepositReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5080b223cb4cee2, []int{1}
}

func (m *DepositReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositReply.Unmarshal(m, b)
}
func (m *DepositReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositReply.Marshal(b, m, deterministic)
}
func (m *DepositReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositReply.Merge(m, src)
}
func (m *DepositReply) XXX_Size() int {
	return xxx_messageInfo_DepositReply.Size(m)
}
func (m *DepositReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositReply.DiscardUnknown(m)
}

var xxx_messageInfo_DepositReply proto.InternalMessageInfo

func (m *DepositReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DepositRequest)(nil), "proto.DepositRequest")
	proto.RegisterType((*DepositReply)(nil), "proto.DepositReply")
}

func init() { proto.RegisterFile("txn_request.proto", fileDescriptor_e5080b223cb4cee2) }

var fileDescriptor_e5080b223cb4cee2 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0xa9, 0xc8, 0x8b,
	0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05,
	0x53, 0x4a, 0x8e, 0x5c, 0x7c, 0x2e, 0xa9, 0x05, 0xf9, 0xc5, 0x99, 0x25, 0x41, 0x10, 0x69, 0x21,
	0x71, 0x2e, 0xf6, 0xd2, 0xe2, 0xd4, 0xa2, 0xf8, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x36, 0x10, 0xd7, 0x33, 0x45, 0x48, 0x8c, 0x8b, 0x2d, 0x31, 0x37, 0xbf, 0x34, 0xaf, 0x44,
	0x82, 0x49, 0x81, 0x51, 0x83, 0x29, 0x08, 0xca, 0x53, 0xd2, 0xe0, 0xe2, 0x81, 0x1b, 0x51, 0x90,
	0x53, 0x29, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x0a, 0x35, 0x00, 0xc6,
	0x35, 0xf2, 0xe1, 0xe2, 0xf1, 0xcd, 0xcf, 0x4b, 0xad, 0x0c, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e,
	0x15, 0xb2, 0x81, 0xeb, 0x04, 0x0b, 0x0b, 0x89, 0x42, 0xdc, 0xa6, 0x87, 0xea, 0x22, 0x29, 0x61,
	0x74, 0xe1, 0x82, 0x9c, 0x4a, 0x25, 0x06, 0x27, 0x03, 0x2e, 0xe9, 0xcc, 0x7c, 0xbd, 0xf4, 0xa2,
	0x82, 0x64, 0xbd, 0xd4, 0x8a, 0xc4, 0xdc, 0x82, 0x9c, 0xd4, 0x62, 0xbd, 0x8c, 0xd4, 0x9c, 0x9c,
	0xfc, 0xf2, 0xfc, 0xa2, 0x9c, 0x14, 0x27, 0x7e, 0x0f, 0x10, 0x3b, 0x1c, 0xc4, 0x0e, 0x00, 0x69,
	0x0f, 0x60, 0x4c, 0x62, 0x03, 0x9b, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x6b, 0xdc, 0xec,
	0xe3, 0x0f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MoneyServiceClient is the client API for MoneyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MoneyServiceClient interface {
	// Sends a greeting
	DepositMoney(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositReply, error)
}

type moneyServiceClient struct {
	cc *grpc.ClientConn
}

func NewMoneyServiceClient(cc *grpc.ClientConn) MoneyServiceClient {
	return &moneyServiceClient{cc}
}

func (c *moneyServiceClient) DepositMoney(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositReply, error) {
	out := new(DepositReply)
	err := c.cc.Invoke(ctx, "/proto.MoneyService/DepositMoney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoneyServiceServer is the server API for MoneyService service.
type MoneyServiceServer interface {
	// Sends a greeting
	DepositMoney(context.Context, *DepositRequest) (*DepositReply, error)
}

func RegisterMoneyServiceServer(s *grpc.Server, srv MoneyServiceServer) {
	s.RegisterService(&_MoneyService_serviceDesc, srv)
}

func _MoneyService_DepositMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyServiceServer).DepositMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MoneyService/DepositMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyServiceServer).DepositMoney(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MoneyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MoneyService",
	HandlerType: (*MoneyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DepositMoney",
			Handler:    _MoneyService_DepositMoney_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "txn_request.proto",
}
