// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account_request.proto

package communication

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type AccountRequest struct {
	AccountNumber        string   `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Balance              float64  `protobuf:"fixed64,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_32ec3829ba78adf1, []int{0}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

func (m *AccountRequest) GetAccountNumber() string {
	if m != nil {
		return m.AccountNumber
	}
	return ""
}

func (m *AccountRequest) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

// The response message containing the greetings
type AccountReply struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountReply) Reset()         { *m = AccountReply{} }
func (m *AccountReply) String() string { return proto.CompactTextString(m) }
func (*AccountReply) ProtoMessage()    {}
func (*AccountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_32ec3829ba78adf1, []int{1}
}

func (m *AccountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountReply.Unmarshal(m, b)
}
func (m *AccountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountReply.Marshal(b, m, deterministic)
}
func (m *AccountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountReply.Merge(m, src)
}
func (m *AccountReply) XXX_Size() int {
	return xxx_messageInfo_AccountReply.Size(m)
}
func (m *AccountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountReply.DiscardUnknown(m)
}

var xxx_messageInfo_AccountReply proto.InternalMessageInfo

func (m *AccountReply) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func init() {
	proto.RegisterType((*AccountRequest)(nil), "communication.AccountRequest")
	proto.RegisterType((*AccountReply)(nil), "communication.AccountReply")
}

func init() { proto.RegisterFile("account_request.proto", fileDescriptor_32ec3829ba78adf1) }

var fileDescriptor_32ec3829ba78adf1 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0x8d, 0x82, 0xd2, 0x87, 0x5b, 0x21, 0x20, 0x2c, 0x96, 0x42, 0x59, 0x10, 0x7a, 0x31,
	0x88, 0xfe, 0x02, 0xeb, 0x45, 0x0f, 0x4a, 0x8d, 0x07, 0x8f, 0x25, 0x9b, 0x7d, 0x68, 0x20, 0xc9,
	0x8b, 0x69, 0xa2, 0xf6, 0xdf, 0xcb, 0x6e, 0x77, 0x0b, 0x3d, 0xf4, 0x36, 0xf9, 0x32, 0x6f, 0x18,
	0x06, 0x2e, 0x95, 0xd6, 0x94, 0x7d, 0x5a, 0x45, 0xfc, 0xce, 0xb8, 0x4e, 0x22, 0x44, 0x4a, 0xc4,
	0x0b, 0x4d, 0xce, 0x65, 0x6f, 0xb4, 0x4a, 0x86, 0x7c, 0xf5, 0x06, 0xe3, 0x87, 0xad, 0x4f, 0x6e,
	0x6d, 0xfc, 0x1a, 0xc6, 0xc3, 0xa5, 0xcf, 0xae, 0xc6, 0x58, 0xb2, 0x19, 0x9b, 0x8f, 0x64, 0xd1,
	0xd3, 0xd7, 0x0e, 0xf2, 0x12, 0xce, 0x6a, 0x65, 0x95, 0xd7, 0x58, 0x1e, 0xcf, 0xd8, 0x9c, 0xc9,
	0xe1, 0x59, 0xdd, 0xc0, 0xf9, 0x2e, 0x32, 0xd8, 0x0d, 0x9f, 0x02, 0x0c, 0x81, 0xa6, 0xe9, 0xc2,
	0x4e, 0xe4, 0xa8, 0x27, 0xcf, 0xcd, 0xdd, 0x6a, 0xd7, 0xe0, 0x1d, 0xe3, 0x8f, 0xd1, 0xc8, 0x5f,
	0xa0, 0x78, 0x8c, 0xa8, 0x12, 0xf6, 0x9c, 0x4f, 0xc5, 0x5e, 0x69, 0xb1, 0xdf, 0xf8, 0x6a, 0x72,
	0xe8, 0x3b, 0xd8, 0x4d, 0x75, 0xb4, 0xb8, 0x85, 0x89, 0x21, 0xf1, 0x19, 0x83, 0x16, 0xf8, 0xa7,
	0x5c, 0xb0, 0xb8, 0x16, 0x5f, 0x68, 0x2d, 0xfd, 0x52, 0xb4, 0xcd, 0xe2, 0xe2, 0xa9, 0xd5, 0x1f,
	0xad, 0x5e, 0xb6, 0x0b, 0x2d, 0x59, 0x7d, 0xda, 0x4d, 0x75, 0xff, 0x1f, 0x00, 0x00, 0xff, 0xff,
	0x6f, 0x8d, 0xee, 0xe7, 0x43, 0x01, 0x00, 0x00,
}
