// Code generated by protoc-gen-go. DO NOT EDIT.
// source: txn_request.proto

package communication

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type DepositRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositRequest) Reset()         { *m = DepositRequest{} }
func (m *DepositRequest) String() string { return proto.CompactTextString(m) }
func (*DepositRequest) ProtoMessage()    {}
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5080b223cb4cee2, []int{0}
}

func (m *DepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositRequest.Unmarshal(m, b)
}
func (m *DepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositRequest.Marshal(b, m, deterministic)
}
func (m *DepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositRequest.Merge(m, src)
}
func (m *DepositRequest) XXX_Size() int {
	return xxx_messageInfo_DepositRequest.Size(m)
}
func (m *DepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositRequest proto.InternalMessageInfo

func (m *DepositRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DepositRequest) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

// The response message containing the greetings
type DepositReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositReply) Reset()         { *m = DepositReply{} }
func (m *DepositReply) String() string { return proto.CompactTextString(m) }
func (*DepositReply) ProtoMessage()    {}
func (*DepositReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5080b223cb4cee2, []int{1}
}

func (m *DepositReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositReply.Unmarshal(m, b)
}
func (m *DepositReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositReply.Marshal(b, m, deterministic)
}
func (m *DepositReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositReply.Merge(m, src)
}
func (m *DepositReply) XXX_Size() int {
	return xxx_messageInfo_DepositReply.Size(m)
}
func (m *DepositReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositReply.DiscardUnknown(m)
}

var xxx_messageInfo_DepositReply proto.InternalMessageInfo

func (m *DepositReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DepositRequest)(nil), "communication.DepositRequest")
	proto.RegisterType((*DepositReply)(nil), "communication.DepositReply")
}

func init() { proto.RegisterFile("txn_request.proto", fileDescriptor_e5080b223cb4cee2) }

var fileDescriptor_e5080b223cb4cee2 = []byte{
	// 226 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x14, 0x85, 0x4d, 0x17, 0x53, 0xbc, 0x54, 0xc5, 0x2c, 0x74, 0xb0, 0x08, 0x65, 0x56, 0xb3, 0x0a,
	0xa2, 0x4f, 0x60, 0x71, 0xa1, 0xa0, 0x50, 0xc6, 0x85, 0x1b, 0xa1, 0xc4, 0xcc, 0xa5, 0x06, 0x92,
	0xdc, 0x98, 0x1f, 0xed, 0xbc, 0xbd, 0xa4, 0xd6, 0x42, 0x17, 0xdd, 0x9d, 0xef, 0xfe, 0x1c, 0x0e,
	0x07, 0xce, 0xd3, 0xda, 0x2d, 0x03, 0x7e, 0x65, 0x8c, 0x49, 0xf8, 0x40, 0x89, 0xf8, 0x89, 0x22,
	0x6b, 0xb3, 0xd3, 0x4a, 0x26, 0x4d, 0xae, 0xb9, 0x87, 0xd3, 0x07, 0xf4, 0x14, 0x75, 0xea, 0xfe,
	0xce, 0xf8, 0x25, 0x8c, 0x73, 0xc4, 0xb0, 0xd4, 0x7d, 0xcd, 0x66, 0xac, 0x3d, 0xee, 0xaa, 0x82,
	0x4f, 0x3d, 0xbf, 0x80, 0x4a, 0x5a, 0xca, 0x2e, 0xd5, 0xa3, 0x19, 0x6b, 0x47, 0xdd, 0x96, 0x9a,
	0x16, 0x26, 0x3b, 0x0b, 0x6f, 0x06, 0x5e, 0xc3, 0xd8, 0x62, 0x8c, 0x72, 0x85, 0x5b, 0x83, 0x7f,
	0xbc, 0x7d, 0x87, 0xc9, 0x0b, 0x39, 0x1c, 0x5e, 0x31, 0x7c, 0x6b, 0x85, 0xfc, 0x79, 0xf7, 0xb9,
	0x19, 0xf3, 0x6b, 0xb1, 0x17, 0x4e, 0xec, 0x27, 0xbb, 0x9a, 0x1e, 0x5a, 0x7b, 0x33, 0x34, 0x47,
	0xf3, 0x1b, 0x98, 0x6a, 0x12, 0xab, 0xe0, 0x95, 0xc0, 0xb5, 0xb4, 0xde, 0x60, 0x14, 0x9f, 0x68,
	0x0c, 0xfd, 0x50, 0x30, 0xfd, 0xfc, 0xec, 0xb1, 0xe8, 0xb7, 0xa2, 0x17, 0xa5, 0x89, 0x05, 0xfb,
	0xa8, 0x36, 0x95, 0xdc, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x69, 0x27, 0xda, 0x27, 0x01,
	0x00, 0x00,
}
